//Product
export const UPDATE_PRODUCT_INPUT = 'UPDATE_PRODUCT_INPUT'

//Package
export const TOGGLE_SELECTED_PRODUCT = 'TOGGLE_SELECTED_PRODUCT'
export const REMOVE_PACKAGE_FROM_LIST = 'REMOVE_PACKAGE_FROM_LIST'
export const UPDATE_PACKAGE_INPUT = 'UPDATE_PACKAGE_INPUT'
export const ADD_PACKAGE = 'ADD_PACKAGE'
export const SET_PACKAGE_LIST = 'SET_PACKAGE_LIST'

//Contact
export const UPDATE_CONTACT_INPUT = 'UPDATE_CONTACT_INPUT'

//Calendar
export const UPDATE_CALENDAR_INPUT = 'UPDATE_CALENDAR_INPUT'
export const SAVE_EVENT = 'SAVE_EVENT'

//Admin
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const TOGGLE_LOADER = 'TOGGLE_LOADER'
export const UPDATE_INPUT = 'UPDATE_INPUT'

//Login
export const UPDATE_LOGIN_FIELD = 'UPDATE_LOGIN_FIELD'
export const SET_TOKEN = 'SET_TOKEN'
export const TOGGLE_LOADER_FIELD = 'TOGGLE_LOADER_FIELD'

//Content
export const UPDATE_CONTENT_FIELD = 'UPDATE_CONTENT_FIELD'
export const SET_CONTENT_MAP = 'SET_CONTENT_MAP'

